version: 2

project_name: vigilante

builds:
  - id: vigilante-linux-amd64
    main: ./cmd/vigilante/main.go
    binary: vigilante
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.x86_64.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static'
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo

  - id: vigilante-darwin-arm64
    main: ./cmd/vigilante/main.go
    binary: vigilante
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib -Wl,-rpath,/lib
    ldflags:
      - -w -s
      - -linkmode=external
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - netgo
      - ledger
      - static_wasm

archives:
  - id: zipped
    builds:
      - vigilante-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - vigilante-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: babylonlabs-io
    name: vigilante

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

dist: dist
