version: 2
project_name: vigilante

env:
  - CGO_ENABLED=1
  - CGO_LDFLAGS=-L/lib

before:
  hooks:
    - wget -nc https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a
    - wget -nc https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /lib/libwasmvm_muslc.aarch64.a
    - wget -nc https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a

    - curl -LO https://musl.cc/x86_64-linux-musl-cross.tgz
    - tar xf x86_64-linux-musl-cross.tgz
    - mv -n -u x86_64-linux-musl-cross /opt/musl-cross-x86_64

    - curl -LO https://musl.cc/aarch64-linux-musl-cross.tgz
    - tar xf aarch64-linux-musl-cross.tgz
    - mv -n -u aarch64-linux-musl-cross /opt/musl-cross-aarch64

builds:
  - id: vigilante-linux-amd64
    main: ./cmd/vigilante/main.go
    binary: vigilante
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=/opt/musl-cross-x86_64/bin/x86_64-linux-musl-gcc
      - LD=/opt/musl-cross-x86_64/bin/x86_64-linux-musl-ld
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
        - -X github.com/babylonlabs-io/vigilante/version.version={{ .Version }}
        - -X github.com/babylonlabs-io/vigilante/version.commit={{ .Commit }}
        - -w -s
        - -linkmode=external
        - -extldflags "-Wl,-z,muldefs -static -z noexecstack"
    tags:
      - muslc
      - netgo
      - osusergo

  - id: vigilante-linux-arm64
    main: ./cmd/vigilante/main.go
    binary: vigilante
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=/opt/musl-cross-aarch64/bin/aarch64-linux-musl-gcc
      - LD=/opt/musl-cross-aarch64/bin/aarch64-linux-musl-ld
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
        - -X github.com/babylonlabs-io/vigilante/version.version={{ .Version }}
        - -X github.com/babylonlabs-io/vigilante/version.commit={{ .Commit }}
        - -w -s
        - -linkmode=external
        - -extldflags "-Wl,-z,muldefs -static -z noexecstack"
    tags:
      - muslc
      - netgo
      - osusergo

  - id: vigilante-darwin
    main: ./cmd/vigilante/main.go
    binary: vigilante
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CGO_CFLAGS=-mmacosx-version-min=10.12
      - CGO_LDFLAGS=-L/lib -mmacosx-version-min=10.12
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/babylonlabs-io/vigilante/version.version={{ .Version }}
      - -X github.com/babylonlabs-io/vigilante/version.commit={{ .Commit }}
      - -w -s
      - -linkmode=external
    tags:
      - ledger
      - netgo
      - static_wasm

archives:
  - ids:
      - vigilante-linux-amd64
      - vigilante-linux-arm64
      - vigilante-darwin
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats: [tar.gz, binary]
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: babylonlabs-io
    name: vigilante

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

dist: dist