queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash
pull_request_rules:
  - name: backport changes to release/v0.24.x branch
    conditions:
      - base=main
      - label=backport-to-release/v0.24.x
    actions:
      backport:
        branches:
          - release/v0.24.x
  - name: automerge to main with label automerge and branch protection passing
    conditions: []
    actions:
      queue: