// Code generated by MockGen. DO NOT EDIT.
// Source: monitor/expected_btcstaking_client.go

// Package monitor is a generated GoMock package.
package monitor

import (
	reflect "reflect"

	types "github.com/babylonlabs-io/babylon/v3/x/btcstaking/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	gomock "github.com/golang/mock/gomock"
)

// MockBabylonBTCStakingClient is a mock of BabylonBTCStakingClient interface.
type MockBabylonBTCStakingClient struct {
	ctrl     *gomock.Controller
	recorder *MockBabylonBTCStakingClientMockRecorder
}

// MockBabylonBTCStakingClientMockRecorder is the mock recorder for MockBabylonBTCStakingClient.
type MockBabylonBTCStakingClientMockRecorder struct {
	mock *MockBabylonBTCStakingClient
}

// NewMockBabylonBTCStakingClient creates a new mock instance.
func NewMockBabylonBTCStakingClient(ctrl *gomock.Controller) *MockBabylonBTCStakingClient {
	mock := &MockBabylonBTCStakingClient{ctrl: ctrl}
	mock.recorder = &MockBabylonBTCStakingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBabylonBTCStakingClient) EXPECT() *MockBabylonBTCStakingClientMockRecorder {
	return m.recorder
}

// BTCDelegation mocks base method.
func (m *MockBabylonBTCStakingClient) BTCDelegation(stakingTxHash string) (*types.QueryBTCDelegationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCDelegation", stakingTxHash)
	ret0, _ := ret[0].(*types.QueryBTCDelegationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCDelegation indicates an expected call of BTCDelegation.
func (mr *MockBabylonBTCStakingClientMockRecorder) BTCDelegation(stakingTxHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCDelegation", reflect.TypeOf((*MockBabylonBTCStakingClient)(nil).BTCDelegation), stakingTxHash)
}

// BTCDelegations mocks base method.
func (m *MockBabylonBTCStakingClient) BTCDelegations(status types.BTCDelegationStatus, pageReq *query.PageRequest) (*types.QueryBTCDelegationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCDelegations", status, pageReq)
	ret0, _ := ret[0].(*types.QueryBTCDelegationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCDelegations indicates an expected call of BTCDelegations.
func (mr *MockBabylonBTCStakingClientMockRecorder) BTCDelegations(status, pageReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCDelegations", reflect.TypeOf((*MockBabylonBTCStakingClient)(nil).BTCDelegations), status, pageReq)
}
