// Code generated by MockGen. DO NOT EDIT.
// Source: monitor/expected_btcstaking_client.go

// Package monitor is a generated GoMock package.
package monitor

import (
	reflect "reflect"

	types "github.com/babylonlabs-io/babylon/v3/x/btcstaking/types"
	gomock "github.com/golang/mock/gomock"
)

// MockBabylonAdaptorClient is a mock of BabylonAdaptorClient interface.
type MockBabylonAdaptorClient struct {
	ctrl     *gomock.Controller
	recorder *MockBabylonAdaptorClientMockRecorder
}

// MockBabylonAdaptorClientMockRecorder is the mock recorder for MockBabylonAdaptorClient.
type MockBabylonAdaptorClientMockRecorder struct {
	mock *MockBabylonAdaptorClient
}

// NewMockBabylonAdaptorClient creates a new mock instance.
func NewMockBabylonAdaptorClient(ctrl *gomock.Controller) *MockBabylonAdaptorClient {
	mock := &MockBabylonAdaptorClient{ctrl: ctrl}
	mock.recorder = &MockBabylonAdaptorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBabylonAdaptorClient) EXPECT() *MockBabylonAdaptorClientMockRecorder {
	return m.recorder
}

// BTCDelegation mocks base method.
func (m *MockBabylonAdaptorClient) BTCDelegation(stakingTxHashHex string) (*Delegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCDelegation", stakingTxHashHex)
	ret0, _ := ret[0].(*Delegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCDelegation indicates an expected call of BTCDelegation.
func (mr *MockBabylonAdaptorClientMockRecorder) BTCDelegation(stakingTxHashHex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCDelegation", reflect.TypeOf((*MockBabylonAdaptorClient)(nil).BTCDelegation), stakingTxHashHex)
}

// DelegationsByStatus mocks base method.
func (m *MockBabylonAdaptorClient) DelegationsByStatus(status types.BTCDelegationStatus, cursor []byte, limit uint64) ([]Delegation, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegationsByStatus", status, cursor, limit)
	ret0, _ := ret[0].([]Delegation)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DelegationsByStatus indicates an expected call of DelegationsByStatus.
func (mr *MockBabylonAdaptorClientMockRecorder) DelegationsByStatus(status, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegationsByStatus", reflect.TypeOf((*MockBabylonAdaptorClient)(nil).DelegationsByStatus), status, cursor, limit)
}

// GetConfirmationDepth mocks base method.
func (m *MockBabylonAdaptorClient) GetConfirmationDepth() (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmationDepth")
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmationDepth indicates an expected call of GetConfirmationDepth.
func (mr *MockBabylonAdaptorClientMockRecorder) GetConfirmationDepth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmationDepth", reflect.TypeOf((*MockBabylonAdaptorClient)(nil).GetConfirmationDepth))
}
